### ISSUE TITLE
Tanks are duplicated with tools from JustDireThings in Neoforge 1.20.4 

### ISSUE THREAD

**Issue by Saereth** [Edivad99/DimStorage#59] opened 2024-07-03 21:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using any of the JustDireThings tools, dimensional tanks are duplicated. This is not the case with normal tools such as the ActuallyAdditions paxel.

### How can I reproduce this bug or crash?

Use JustDireThings tools to break dimensional tanks.
You can see a video of it happening in the original issue reported here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5341

### Configuration

```markdown
- Mod version:DimStorage-1.20.4-8.1.0
- Forge version:20.4.237
- Minecraft version:1.20.4
```

### Anything else?

I also opened an issue here 
https://github.com/Direwolf20-MC/JustDireThings/issues/68

**Comment by Edivad99** [comment] 2024-07-04 07:05
Duplicate of #58
Fixed in the next release of DimStorage for 1.20.4

**Closed as completed by Edivad99** 2024-07-04 07:05 UTC
Labels: duplicate
